### ISSUE TITLE
Baxterのシミュレータをつかってみる

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2015-semi#2]

**Comment by k-okada** [comment]
https://github.com/RethinkRobotics/baxter_simulator

**Comment by k-okada** [comment]
インストール方法　http://sdk.rethinkrobotics.com/wiki/Simulator_Installation

**Comment by knorth55** [comment]
baxterのsimulationをインストールしてキーボード操作できるようになりました

**Comment by k-okada** [comment]
すばらしい
https://github.com/RethinkRobotics/baxter_simulator/pull/52
でgripperのシミュレーションができるはずだけど，試せるかな．（動くかな）

**Comment by k-okada** [comment]
@wkentaro, @Tnoriaki　に聞いてAPCの環境をシミュレーションできるといいですね．

**Comment by knorth55** [comment]
gripperのシミュレーションもできました。
![screenshot from 2015-10-27 23 54 36](https://cloud.githubusercontent.com/assets/9300063/10761800/5922a8b2-7d06-11e5-8b64-f2a19ed67f79.png)

**Comment by wkentaro** [comment]
> @wkentaro, @Tnoriaki　に聞いてAPCの環境をシミュレーションできるといいですね．

```
git clone https://github.com/start-jsk/jsk_apc
rosdep install --from-path . -r -y -I
cd jsk_apc/jsk_2015_apc_common
catkin bt
roslaunch gazebo_ros empty_world.launch
```

の後Insert からモデルを挿入すると以下のように出来ます。

![](https://cloud.githubusercontent.com/assets/4310419/10767704/be38b9ac-7d20-11e5-9418-bb06826ee50f.png)

**Comment by knorth55** [comment]
Insertしてモデルを追加することが出来ました。

roslaunch baxter_gazebo baxter_world.launch
rosrun baxter_interface joint_trajectory_action_server.py
rosrun baxter_interface head_action_server.py
を起動した状態でroseus baxter-interface.lを起動すると_baxter_が読み込まれません。
(setq _baxter_ (instance baxter-robot :init))が行われていないのではないかと困っています。

```
[baxter - http://localhost:11311] mech-user@test1-pc:/opt/ros/indigo/share/baxtereus$ roseus baxter-interface.l 
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x5f86de0[16374] --> 0x63e2990[32748] top=3f7f
irtgl irtviewer 
EusLisp 9.15( 1.0.10) for Linux64 created on host02.storm.ros.org(Mon Aug 31 15:37:47 UTC 2015)
roseus ;; loading roseus("") on euslisp((9.15 host02.storm.ros.org Mon Aug 31 15:37:47 UTC 2015  1.0.10))
eustf roseus_c_util (instance r1                        
nil
1.irteusgl$ (instance baxter-robot :init)
#<baxter-robot #X7311cb8 baxter  0.0 0.0 0.0 / 0.0 0.0 0.0>
2.irteusgl$ *baxter*
sh: 1: baxter-interface.l: not found
32512
3.irteusgl$ setq *baxter* (instance baxter-robot :init)
#<baxter-robot #X679f1e8 baxter  0.0 0.0 0.0 / 0.0 0.0 0.0>
4.irteusgl$ *baxter*
#<baxter-robot #X679f1e8 baxter  0.0 0.0 0.0 / 0.0 0.0 0.0>
```

**Comment by knorth55** [comment]
bazxter-initをするのを忘れていました。baxter-initをすれば動きました。

**Comment by knorth55** [comment]
BaxterのシミュレーターでMove Itを扱おうとすると下記のようなエラーが出ます。

```
[baxter - http://localhost:11311] mech-user@test1-pc:~/jsk-semi/baxter_sample$ rqt 
cannot ping [/move_group]: unknown node
PluginManager._load_plugin() could not load plugin "rqt_moveit/Moveit":
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
    self._load()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 94, in load
    return class_ref(plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_moveit/moveit_plugin.py", line 47, in __init__
    self._moveit_widget = MoveitWidget(self, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_moveit/moveit_widget.py", line 111, in __init__
    self.sig_sysmsg = self._widget_topic.sig_sysmsg
AttributeError: 'TopicWidget' object has no attribute 'sig_sysmsg'
```

調べてみたところrqt_moveitのgithubにも同じissueを書いている人がいました。
https://github.com/ros-visualization/rqt_robot_plugins/issues/77

**Comment by knorth55** [comment]
またrqtをおこなってJoint trajectory controllerを行っても選択するcontrollerに何も表示されない問題も解決していません。
![screenshot from 2015-11-02 23 06 05](https://cloud.githubusercontent.com/assets/9300063/10883654/ba25b9b0-81b6-11e5-887b-65d97c4009c2.png)

rosserviceで呼び出してみたところcontrollerはlist_controllersとlist_controller_typesには入っているようです。

```
[baxter - http://localhost:11311] mech-user@test1-pc:~/jsk-semi/baxter_sample/src$ rosservice call /robot/controller_manager/list_controllers
controller: 
  - 
    name: joint_state_controller
    state: running
    type: joint_state_controller/JointStateController
    hardware_interface: hardware_interface::JointStateInterface
    resources: []
  - 
    name: left_joint_position_controller
    state: running
    type: baxter_sim_controllers/BaxterPositionController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['left_e0', 'left_e1', 'left_s0', 'left_s1', 'left_w0', 'left_w1', 'left_w2']
  - 
    name: right_joint_position_controller
    state: running
    type: baxter_sim_controllers/BaxterPositionController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['right_e0', 'right_e1', 'right_s0', 'right_s1', 'right_w0', 'right_w1', 'right_w2']
  - 
    name: head_position_controller
    state: stopped
    type: baxter_sim_controllers/BaxterHeadController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['head_pan']
  - 
    name: left_joint_velocity_controller
    state: stopped
    type: baxter_sim_controllers/BaxterVelocityController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['left_e0', 'left_e1', 'left_s0', 'left_s1', 'left_w0', 'left_w1', 'left_w2']
  - 
    name: right_joint_velocity_controller
    state: stopped
    type: baxter_sim_controllers/BaxterVelocityController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['right_e0', 'right_e1', 'right_s0', 'right_s1', 'right_w0', 'right_w1', 'right_w2']
  - 
    name: left_joint_effort_controller
    state: stopped
    type: baxter_sim_controllers/BaxterEffortController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['left_e0', 'left_e1', 'left_s0', 'left_s1', 'left_w0', 'left_w1', 'left_w2']
  - 
    name: right_joint_effort_controller
    state: stopped
    type: baxter_sim_controllers/BaxterEffortController
    hardware_interface: hardware_interface::EffortJointInterface
    resources: ['right_e0', 'right_e1', 'right_s0', 'right_s1', 'right_w0', 'right_w1', 'right_w2']
```

```
[baxter - http://localhost:11311] mech-user@test1-pc:~/jsk-semi/baxter_sample/src$ rosservice call /robot/controller_manager/list_controller_types 
types: ['baxter_sim_controllers/BaxterEffortController', 'baxter_sim_controllers/BaxterHeadController', 'baxter_sim_controllers/BaxterPositionController', 'baxter_sim_controllers/BaxterVelocityController', 'controller_manager_tests/EffortTestController', 'controller_manager_tests/MyDummyController', 'diff_drive_controller/DiffDriveController', 'effort_controllers/GripperActionController', 'effort_controllers/JointEffortController', 'effort_controllers/JointGroupEffortController', 'effort_controllers/JointPositionController', 'effort_controllers/JointTrajectoryController', 'effort_controllers/JointVelocityController', 'force_torque_sensor_controller/ForceTorqueSensorController', 'imu_sensor_controller/ImuSensorController', 'joint_state_controller/JointStateController', 'position_controllers/GripperActionController', 'position_controllers/JointGroupPositionController', 'position_controllers/JointPositionController', 'position_controllers/JointTrajectoryController', 'velocity_controllers/JointGroupVelocityController', 'velocity_controllers/JointPositionController', 'velocity_controllers/JointTrajectoryController', 'velocity_controllers/JointVelocityController']
base_classes: ['controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase', 'controller_interface::ControllerBase']
```
